### ISSUE TITLE
white screen When not logged in

### ISSUE THREAD

**Issue by wiwatsrt** [wiwatsrt/flarum-ext-best-answer#1]
When not logged in, and this is turned on, I cannot see any thread. It's a complete white screen.

Once logged in like normal, all threads start showing again.

@sheldon
https://discuss.flarum.org/d/3868-select-post-best-answer/7

**Comment by sheldon** [comment]
I think you have the wrong Sheldon :)

**Comment by wiwatsrt** [comment]
I 'm sorry fot mentions.
